resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 10
        waitDuration: 500
    instances:
      getPrice:
        baseConfig: default
        resultPredicate: com.poc.resilience.predicate.ResiliencePredicate
